"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Televisor_1 = require("../Ejercicio 3/Televisor");
var Decodificador_1 = require("./Decodificador");
var tv1 = new Televisor_1.Televisor("Noblex");
var tv2 = new Televisor_1.Televisor("Sanyo");
var tv3 = new Televisor_1.Televisor("Samsung con decodificador Decopro");
var decopro = new Decodificador_1.Decodificador(tv3, "Decopro");
tv1.prenderTv();
tv1.subirCanal();
tv1.subirCanal();
tv1.subirVolumen();
tv1.subirVolumen();
tv1.subirVolumen();
tv1.info();
tv1.selecCanal(98);
tv1.subirCanal();
tv1.subirCanal();
tv1.info();
tv1.prenderTv();
tv1.info();
tv2.prenderTv();
tv2.bajarCanal();
tv2.bajarVolumen();
tv2.info();
tv2.prenderTv();
tv2.info();
tv3.prenderTv();
tv3.info();
decopro.subirCanalDeco();
decopro.subirCanalDeco();
decopro.subirCanalDeco();
decopro.subirCanalDeco();
tv3.info();
decopro.bajarCanalDeco();
decopro.bajarCanalDeco();
tv3.info();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
tv3.info();
decopro.bajarVolDeco();
decopro.bajarVolDeco();
tv3.info();
decopro.bajarVolDeco();
decopro.bajarVolDeco();
decopro.bajarVolDeco();
decopro.bajarVolDeco();
decopro.bajarVolDeco();
tv3.info();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
decopro.subirVolDeco();
tv3.info();
tv3.prenderTv();
tv3.info();
