"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Libro_1 = require("../Ejercicio 5/Libro");
var GestorLibros_1 = require("./GestorLibros");
var libro1 = new Libro_1.Libro();
var libro2 = new Libro_1.Libro();
var libro3 = new Libro_1.Libro();
var gestor = new GestorLibros_1.GestorLibros();
// libro1.cargarLibro ();
// libro2.cargarLibro ();
// libro3.cargarLibro ();
// libro1.infoLibro ();
// libro2.infoLibro ();
// libro3.infoLibro ();
gestor.insertarLibro();
gestor.insertarLibro();
gestor.insertarLibro();
gestor.consultarLibro();
gestor.consultarLibro();
gestor.consultarLibro();
gestor.modificarLibro();
gestor.eliminarLibro();
gestor.consultarLibro();
gestor.consultarLibro();
